# Generated by Django 4.2.2 on 2024-11-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', 'XXXX_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.AlterField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
