# Generated by Django 4.2.2 on 2024-11-05 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_remove_userprofile_pinned_entry_pinnedentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveditem',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='question',
        ),
    ]
