# Generated by Django 4.2.2 on 2024-10-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vote_vote_unique_user_question_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='from_search',
            field=models.BooleanField(default=False),
        ),
    ]
