# Generated by Django 4.2.2 on 2024-10-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_answer_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='button_hover_background_color',
            field=models.CharField(default='#0056b3', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dropdown_hover_background_color',
            field=models.CharField(default='#f2f2f2', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dropdown_hover_text_color',
            field=models.CharField(default='#0056b3', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dropdown_text_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hover_background_color',
            field=models.CharField(default='#f0f0f0', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icon_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icon_hover_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link_hover_color',
            field=models.CharField(default='#0056b3', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nav_link_hover_bg',
            field=models.CharField(default='rgba(0, 0, 0, 0.05)', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nav_link_hover_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pagination_active_background_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pagination_active_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pagination_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pagination_text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
