# Generated by Django 4.2.2 on 2024-11-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_vote_unique_user_question_vote_and_more'),
    ]

    operations = [
    ]
